core/config/routes.rb
Brightcontent::Engine.routes.draw do
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :admin_users
  resources :sessions, only: [:new, :create, :destroy]

  root to: "admin_users#index"
end

core/app/models/brightcontent/admin_user.rb
module Brightcontent
  class AdminUser < ActiveRecord::Base
    has_secure_password
    validates_uniqueness_of :email
  end
end

core/app/controllers/brightcontent/admin_users_controller.rb
require_dependency "brightcontent/application_controller"

module Brightcontent
  class AdminUsersController < BaseController
    def form_fields
      %w( email password password_confirmation )
    end
  end
end

core/app/controllers/brightcontent/application_controller.rb
module Brightcontent
  class ApplicationController < ActionController::Base
    before_filter :authorize

    private

    def current_user
      @current_user ||= AdminUser.find(session[:brightcontent_user_id]) if session[:brightcontent_user_id]
    end
    helper_method :current_user

    def user_resources
      @user_resources ||= RoutesParser.new.resources
    end
    helper_method :user_resources

    def authorize
      redirect_to login_url if current_user.nil?
    end

  end
end

core/app/controllers/brightcontent/base_controller.rb
require 'csv'
require_dependency "brightcontent/application_controller"

module Brightcontent
  class BaseController < ApplicationController
    inherit_resources
    helper_method :scopes_configuration
    respond_to :all

    include DefaultActions
    include Pagination

    protected

    def permitted_params
      params.permit!
    end
    
    def list_fields
      default_fields - %w{attachments}
    end
    helper_method :list_fields

    def form_fields
      default_fields
    end
    helper_method :form_fields

    def default_fields
      resource_class.brightcontent_columns - %w{id created_at updated_at password_digest}
    end
    helper_method :default_fields

    def parent
      super if parent?
    end
    helper_method :parent

    def resource_item_path
      [parent, resource]
    end
    helper_method :resource_item_path

    def resource_index_path
      [parent, resource_class]
    end
    helper_method :resource_index_path

  end
end

core/app/controllers/brightcontent/sessions_controller.rb
module Brightcontent
  class SessionsController < ApplicationController
    skip_before_filter :authorize

    def new
    end

    def create
      user = AdminUser.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:brightcontent_user_id] = user.id
        redirect_to root_url
      else
        flash.now.alert = "Email or password is invalid"
        render :new
      end
    end

    def destroy
      session[:brightcontent_user_id] = nil
      redirect_to root_url
    end
  end
end

core/app/helpers/brightcontent/application_helper.rb
module Brightcontent
  module ApplicationHelper
  end
end

core/app/helpers/brightcontent/base_helper.rb
module Brightcontent
  module BaseHelper
    def render_list_field(item, field)
      render_if_exists("list_field_#{field}", item: item) || item.send(field).to_s.truncate(50)
    end

    def render_form_field(form, field)
      render_if_exists("form_field_#{field}", form: form, item: form.object) ||
      render_if_exists("brightcontent/fields/#{field_type(form, field)}", form: form, item: form.object, field: field) ||
      form.input(field.to_sym)
    end

    def link_for_scope(scope)
      case scope[:type]
      when :boolean
        polymorphic_url(resource_index_path, scope[:as] => true)
      end
    end

    private

    def render_if_exists(*args)
      render *args
    rescue ActionView::MissingTemplate
      nil
    end

    def field_type(form, field)
      column = form.send(:find_attribute_column, field)
      form.send(:default_input_type, field, column, {})
    end
  end
end

core/app/views/brightcontent/application/_menu.html.erb
<% user_resources.each do |resource| %>
  <li><%= link_to resource.klass.model_name.human.pluralize, root_path + resource.path %></li>
<% end %>

core/app/views/brightcontent/application/_show_flash_names.html.erb
<% flash.each do |key,value| %>
  <div class="alert alert-<%= key.to_s%>">
    <%= value %>
  </div>
<% end %>

core/app/views/brightcontent/base/_form.html.erb
<%= simple_form_for resource_item_path do |form| -%>
  <%= form.error_notification %>

  <div class="form-inputs">
    <% form_fields.each do |form_field| -%>
      <%= render_form_field(form, form_field) -%>
    <% end -%>
  </div>

  <%= form.button :submit, class: "btn btn-primary" %>
  <%= form.button :submit, "Save and continue", :name => "commit_and_continue" %>

  <% unless resource.new_record? -%>
    <%= link_to "Delete", resource_item_path, :class => "btn btn-danger delete", :method => :delete, :data => { :confirm => 'Are you sure?' } %>
  <% end -%>

<% end -%>

core/app/views/brightcontent/base/_list.html.erb
<% collection.each do |item| %>
  <%= content_tag_for :tr, item do %>
    <% list_fields.each do |field| %>
      <td><%= render_list_field(item, field) %></td>
    <% end %>
    <td class="list-actions"><%= render "list_actions", item: item %></td>
  <% end %>
<% end %>

core/app/views/brightcontent/base/_list_actions.html.erb
<%= link_to "Edit", [:edit, parent, item], class: "btn btn-mini btn-primary" %>
<%= link_to "Delete", [parent, item], class: "btn btn-mini", confirm: 'Are you sure?', method: :delete %>

core/app/views/brightcontent/base/_scope_filters.html.erb
<ul class="nav nav-pills">
  <li class="disabled"><a href="#">Filter: </a></li>
  <% scopes_configuration.each do |scope| %>
    <li>
      <%= link_to scope[1][:as].to_s.humanize, link_for_scope(scope[1]) %> 
    </li>
  <% end %>
</ul>

core/app/views/brightcontent/base/edit.html.erb
<h1>Edit <%= resource_class.model_name.human %></h1>

<%= render "form" %>

core/app/views/brightcontent/base/index.csv.erb
<%== CSV.generate(:col_sep => ";", :quote_char => '"') do |csv| %>
  <% csv << default_fields %>
  <% collection.each do |item| %>
    <% csv << default_fields.map { |field| item.send(field) } %>
  <% end %>
<% end %>

core/app/views/brightcontent/base/index.html.erb
<div id="overview">

  <%= link_to "Create new #{resource_instance_name.to_s.humanize}", polymorphic_url(resource_index_path, action: :new), class: "btn btn-primary btn-right" %>
  <h1><%= resource_class.model_name.human.pluralize %></h1>

  <%= render "scope_filters" if scopes_configuration %>
  <%= render "index_top" %>

  <table class="table table-hover">
    <thead>
      <tr>
        <% list_fields.each do |list_field| %>
          <th><%= list_field.humanize %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render "list", collection: collection, list_fields: list_fields  %>
    </tbody>
  </table>

  <%= will_paginate collection %>

</div>

core/app/views/brightcontent/base/new.html.erb
<h1>Create new <%= resource_instance_name.to_s %></h1>

<%= render "form" %>

core/app/views/brightcontent/fields/_file.html.erb
<% if item.send(field).present? %>
  <div class="controls file-preview">
    <%= image_tag item.send(field).url(item.send(field).styles.keys.first) %>
  </div>
<% end %>
<%= form.input field %>

core/app/views/layouts/brightcontent/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brightcontent</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "brightcontent/brightcontent", :media => "all" %>
  <%= javascript_include_tag "brightcontent/brightcontent" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>


  <% if current_user %>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to Brightcontent.application_name, root_path, class: "brand" %>
          <div class="nav-collapse collapse">
            <ul class="nav" id="menu">
              <%= render "menu" %>
            </ul>
            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Homepage", "/" %></li>
                  <li><%= link_to "Admins", admin_users_path %></li>
                  <li><%= link_to "Logout", logout_path %></li>
                <ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="container <%= "box" unless controller.controller_name == 'sessions' %>">
    <%= render "brightcontent/application/show_flash_names" %>
    <%= yield %>
  </div>

</div>

</body>
</html>