attachments/config/routes.rb
Brightcontent::Engine.routes.draw do
  # TODO: put instead of create
  get 'attachments/:type/:id' => 'attachments#show', as: :attachments
  put 'attachments' => 'attachments#create', as: :new_attachment
  delete 'attachments/:id' => 'attachments#destroy', as: :destroy_attachment
end

attachments/app/models/brightcontent/attachment.rb
module Brightcontent
  class Attachment < ActiveRecord::Base
    belongs_to :attachable, polymorphic: true, :inverse_of => :attachments
    has_attached_file :asset, :styles => lambda {|attachment| attachment.instance.attachment_styles }
    before_post_process :resize_images

    default_scope order("id")

    delegate :url, to: :asset

    validates :asset, attachment_presence: true

    def attachment_styles
      default_attachment_styles.merge(user_defined_styles)
    end

    def image?
      asset_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}
    end

    private

    def user_defined_styles
      if attachable && attachable.class.attachment_styles && image?
        attachable.class.attachment_styles
      end || {}
    end

    def default_attachment_styles
      { brightcontent: "100x100#", main: "200x200#" }
    end

    def resize_images
      return false unless image?
    end

  end
end

attachments/app/controllers/brightcontent/attachments_controller.rb
require_dependency "brightcontent/application_controller"

module Brightcontent
  class AttachmentsController < ApplicationController

    def show
      @attachments = Attachment.where(attachable_type: params[:type].classify, attachable_id: params[:id])
      render layout: false
    end

    def create
      @attachment = Attachment.new(attachment_params)
      if @attachment.save
        render json: @attachment.to_json, status: :created
      else
        render json: @attachment.errors, status: :unprocessable_entity
      end
    end

    def destroy
      attachment = Attachment.destroy(params[:id])
      redirect_to attachment.attachable
    end

    private

    def attachment_params
      params.permit(:attachable_id, :attachable_type, :asset)
    end

  end
end

attachments/app/helpers/brightcontent/attachments_helper.rb
module Brightcontent
  module AttachmentsHelper
  end
end

attachments/app/views/brightcontent/attachments/_attachment.html.erb
<%= div_for attachment do %>
  <% if attachment.image? %>
    <%= image_tag attachment.url(:brightcontent) %>
    <%= link_to "Insert", nil, class: "insert insert_image btn btn-mini", data: { insert_image: attachment.url(:main) } %>
  <% else %>
    <div class="attachment-file"><%= attachment.asset_file_name %></div>
    <%= link_to "Insert", nil, class: "insert insert_link btn btn-mini", data: { insert_url: attachment.url(:original), insert_name: attachment.asset_file_name } %>
  <% end %>
  <%= link_to "Delete", destroy_attachment_path(attachment.id), method: :delete, confirm: "Are you sure?", class: "delete btn btn-danger btn-mini" %>
<% end %>

attachments/app/views/brightcontent/attachments/show.html.erb
<%= render @attachments %>

attachments/app/views/brightcontent/base/_form_field_attachments.html.erb
<div class="control-group optional">
  <label class="optional control-label">Attachments</label>
  <div class="controls">
    <% if item.persisted? %>
      <div id="attachments" class="clearfix">
        <%= render item.attachments %>
      </div>

      <input id="fileupload" type="file" name="asset" data-url="<%= new_attachment_path %>" multiple>
      <%= hidden_field_tag "attachable_id", item.id %>
      <%= hidden_field_tag "attachable_type", item.class.to_s %>
      <%= hidden_field_tag "attachable_url", attachments_path(item.class.to_s, item.id) %>

    <% else %>
      First save to enable uploads
    <% end %>
  </div>
</div>